language: ruby
rvm: 2.3.3
env: RAILS_ENV=test
services:
  - postgresql
script:
  - bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:migrate
install: bundle install --jobs=3 --retry=3
